apiVersion: v1
kind: Service
metadata:
  name: l-tech-server-service
spec:
  # MUST have a space after the colon
  type: NodePort 
  selector:
    app: l-tech-server
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 5000 
      nodePort: 30080